package com.demo.po;

import java.math.BigDecimal;

public class Fund {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_fund.id
     *
     * @mbg.generated Mon Jun 03 17:52:07 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_fund.orgId
     *
     * @mbg.generated Mon Jun 03 17:52:07 CST 2019
     */
    private String orgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_fund.orgName
     *
     * @mbg.generated Mon Jun 03 17:52:07 CST 2019
     */
    private String orgname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_fund.orgNo
     *
     * @mbg.generated Mon Jun 03 17:52:07 CST 2019
     */
    private String orgno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_fund.orgCode
     *
     * @mbg.generated Mon Jun 03 17:52:07 CST 2019
     */
    private String orgcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_fund.yearly
     *
     * @mbg.generated Mon Jun 03 17:52:07 CST 2019
     */
    private String yearly;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_fund.preFund
     *
     * @mbg.generated Mon Jun 03 17:52:07 CST 2019
     */
    private BigDecimal prefund;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_fund.businessFund
     *
     * @mbg.generated Mon Jun 03 17:52:07 CST 2019
     */
    private BigDecimal businessfund;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_fund.dutyFund
     *
     * @mbg.generated Mon Jun 03 17:52:07 CST 2019
     */
    private BigDecimal dutyfund;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_d0_fund.buildFund
     *
     * @mbg.generated Mon Jun 03 17:52:07 CST 2019
     */
    private BigDecimal buildfund;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_fund.id
     *
     * @return the value of t_d0_fund.id
     *
     * @mbg.generated Mon Jun 03 17:52:07 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_fund.id
     *
     * @param id the value for t_d0_fund.id
     *
     * @mbg.generated Mon Jun 03 17:52:07 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_fund.orgId
     *
     * @return the value of t_d0_fund.orgId
     *
     * @mbg.generated Mon Jun 03 17:52:07 CST 2019
     */
    public String getOrgid() {
        return orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_fund.orgId
     *
     * @param orgid the value for t_d0_fund.orgId
     *
     * @mbg.generated Mon Jun 03 17:52:07 CST 2019
     */
    public void setOrgid(String orgid) {
        this.orgid = orgid == null ? null : orgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_fund.orgName
     *
     * @return the value of t_d0_fund.orgName
     *
     * @mbg.generated Mon Jun 03 17:52:07 CST 2019
     */
    public String getOrgname() {
        return orgname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_fund.orgName
     *
     * @param orgname the value for t_d0_fund.orgName
     *
     * @mbg.generated Mon Jun 03 17:52:07 CST 2019
     */
    public void setOrgname(String orgname) {
        this.orgname = orgname == null ? null : orgname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_fund.orgNo
     *
     * @return the value of t_d0_fund.orgNo
     *
     * @mbg.generated Mon Jun 03 17:52:07 CST 2019
     */
    public String getOrgno() {
        return orgno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_fund.orgNo
     *
     * @param orgno the value for t_d0_fund.orgNo
     *
     * @mbg.generated Mon Jun 03 17:52:07 CST 2019
     */
    public void setOrgno(String orgno) {
        this.orgno = orgno == null ? null : orgno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_fund.orgCode
     *
     * @return the value of t_d0_fund.orgCode
     *
     * @mbg.generated Mon Jun 03 17:52:07 CST 2019
     */
    public String getOrgcode() {
        return orgcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_fund.orgCode
     *
     * @param orgcode the value for t_d0_fund.orgCode
     *
     * @mbg.generated Mon Jun 03 17:52:07 CST 2019
     */
    public void setOrgcode(String orgcode) {
        this.orgcode = orgcode == null ? null : orgcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_fund.yearly
     *
     * @return the value of t_d0_fund.yearly
     *
     * @mbg.generated Mon Jun 03 17:52:07 CST 2019
     */
    public String getYearly() {
        return yearly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_fund.yearly
     *
     * @param yearly the value for t_d0_fund.yearly
     *
     * @mbg.generated Mon Jun 03 17:52:07 CST 2019
     */
    public void setYearly(String yearly) {
        this.yearly = yearly == null ? null : yearly.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_fund.preFund
     *
     * @return the value of t_d0_fund.preFund
     *
     * @mbg.generated Mon Jun 03 17:52:07 CST 2019
     */
    public BigDecimal getPrefund() {
        return prefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_fund.preFund
     *
     * @param prefund the value for t_d0_fund.preFund
     *
     * @mbg.generated Mon Jun 03 17:52:07 CST 2019
     */
    public void setPrefund(BigDecimal prefund) {
        this.prefund = prefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_fund.businessFund
     *
     * @return the value of t_d0_fund.businessFund
     *
     * @mbg.generated Mon Jun 03 17:52:07 CST 2019
     */
    public BigDecimal getBusinessfund() {
        return businessfund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_fund.businessFund
     *
     * @param businessfund the value for t_d0_fund.businessFund
     *
     * @mbg.generated Mon Jun 03 17:52:07 CST 2019
     */
    public void setBusinessfund(BigDecimal businessfund) {
        this.businessfund = businessfund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_fund.dutyFund
     *
     * @return the value of t_d0_fund.dutyFund
     *
     * @mbg.generated Mon Jun 03 17:52:07 CST 2019
     */
    public BigDecimal getDutyfund() {
        return dutyfund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_fund.dutyFund
     *
     * @param dutyfund the value for t_d0_fund.dutyFund
     *
     * @mbg.generated Mon Jun 03 17:52:07 CST 2019
     */
    public void setDutyfund(BigDecimal dutyfund) {
        this.dutyfund = dutyfund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d0_fund.buildFund
     *
     * @return the value of t_d0_fund.buildFund
     *
     * @mbg.generated Mon Jun 03 17:52:07 CST 2019
     */
    public BigDecimal getBuildfund() {
        return buildfund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d0_fund.buildFund
     *
     * @param buildfund the value for t_d0_fund.buildFund
     *
     * @mbg.generated Mon Jun 03 17:52:07 CST 2019
     */
    public void setBuildfund(BigDecimal buildfund) {
        this.buildfund = buildfund;
    }
}